#!/bin/bash
# Install all packages using fcpkgmon utility over category loop.
# Author : Anand Kulkarni
# Synopsis : Administration Utility to simplify new upgrades or build out of Fedora Workstation.

export validCategoryList="games wine multimedia tools products langs db"
for categoryItem in $validCategoryList
do
  fcpkgmon all ${categoryItem} 2>&1 | tee -a ${categoryItem}.install.log
done

# Exit with grace.
exit 0
