#!/usr/bin/bash

# Maintain config list here. The first and second list have corrosponding file and where they are to be copied.
export installFiles=("fcpkgmon" "fcpkgmon.conf" "fcpkgmonlib" "fcpkgmonList.txt")
export installFilePaths=("/usr/local/bin" "/etc" "/usr/local/lib" "/etc" "/opt/fcpkgmon")
export installDirs=("custom")
export installDirPaths=("/opt/fcpkgmon")

# Install the items now.
for i in ${!installFiles[@]};
do
	installFile=${installFiles[$i]}
	installFolder=${installFilePaths[$i]}
	cp ./${installFile} ${installFolder}
done

for j in ${!installDirs[@]}
do
	installDir=${installDirs[$j]}
	installPath=${installDirPaths[$j]}
	cp -r ./${installDir} ${installPath}
done

# Auto generate the file list required by the rpm for the package spec file.
fileList="/usr/local/bin/fcpkgmon /etc/fcpkgmonList.txt /etc/fcpkgmon.conf /usr/local/lib/fcpkgmonlib"
outFile="/tmp/fcpkgmon.spec.fileList.txt"

for fileItem in $fileList
do
  echo -e $fileItem>>$outFile
done

# Add all the files to the above list which are in /opt/fcpkgmon/custom path.
find /opt/fcpkgmon/custom|sort|uniq>>$outFile
